var langData = {
  'ar':	'Arabic',
  'ca':	'Catalan',
  'zh-Hans': 'Chinese(Simplified)',
  'zh-Hant': 'Chinese(Traditional)',
  'hr':	'Croatian',
  'cs':	'Czech',
  'nl':	'Dutch',
  'da':   'Danish',
  'en':   'English',
  'en-GB': 'English (British)',
  'en-AU': 'English (Australian)',
  'fi':	'Finnish',
  'fr':	'French',
  'de':	'German',
  'el':	'Greek',
  'he':	'Hebrew',
  'hu':	'Hungarian',
  'id':	'Indonesian',
  'it':	'Italian',
  'ja':	'Japanese',
  'ko':	'Korean',
  'es-MX': 'Mexican Spanish',
  'ms':	'Malay',
  'nb':	'Norwegian (Bokmal)',
  'pl':	'Polish',
  'pt':	'Portuguese',
  'pt-PT': 'Portuguese (Portugal)',
  'ro':	'Romanian',
  'ru':	'Russian',
  'sk':	'Slovak',
  'es':	'Spanish',
  'sv':	'Swedish',
  'th':	'Thai',
  'tr':	'Turkish',
  'uk':	'Ukrainian',
  'vi':	'Vietnamese'
};



